---
# https://splunk.github.io/docker-splunk/ADVANCED.html#runtime-configuration

config:
  baked: default.yml
  defaults_dir: /tmp/defaults
  env:
    headers: null
    var: SPLUNK_DEFAULTS_URL
    verify: true
  host:
    headers: null
    url: null
    verify: true
  max_delay: 60
  max_retries: 3
  max_timeout: 1200

docker: true

hide_password: false

java_download_url: null
java_update_version: null
java_version: null

retry_delay: 6
retry_num: 60

splunk:
  admin_user: admin
  app_paths:
    default: /opt/splunk/etc/apps
  disable_popups: true
  exec: /opt/splunk/bin/splunk
  group: splunk
  home: /opt/splunk
  http_port: 8000

splunk_home_ownership_enforcement: false
splunkbase_password: null
splunkbase_token: null
splunkbase_username: null
wait_for_splunk_retry_num: 60
